### ISSUE TITLE
Registration: Popup message on Register is unclear

### ISSUE THREAD

**Issue by Jaybomb** [daradermody/iigl#33]
# Symptom
Popup message doesn’t make a whole lot of sense. Perhaps something like “Verification email sent to “<email>””

# Steps

- Company Email: jaybopper@hotmail.com
- Battlefy Username: rebulah
- Password: thisisatest
- Confirm Password: thisisatest
- Games Selected: LoL, OW, HS
- Clicked “Register”

# Results

- Message popped up saying Registration user has been sent
- Received email from IIGL (irishinterfirmsgaming@gmail.com)
- Verification Link returns me to the site

**Comment by daradermody** [comment]
Fixed in 2417f44
