### ISSUE TITLE
Registration: Popup message for mismatching passwords is unclear

### ISSUE THREAD

**Issue by Jaybomb** [daradermody/iigl#34]
# Symptom
Popup message when you click on register is not descriptive enough. Should say “Passwords do not match”

# Steps
- Company Email: jaybopper@hotmail.com
- Battlefy Username: rebulah
- Password: thisisatest
- Confirm Password: thisisatest2
- Games Selected: LoL, OW, HS
- Clicked “Register”

# Results
- “Confirm Password” box outlined in red
- Clicking on “Register” displays "The form is not complete"

**Comment by daradermody** [comment]
Fixed in 2417f44ab0
