### ISSUE TITLE
Registration: Popup message for invalid email address is unclear

### ISSUE THREAD

**Issue by Jaybomb** [daradermody/iigl#36]
# Symptom
- Clicking on “Register” displays "The form is not complete"

# Steps
- Company Email: jaybopper’hotmail.com
- Battlefy Username: rebulah
- Password: wasd
- Confirm Password: wasd
- Games Selected: LoL, OW, HS
- Clicked “Register”

**Comment by daradermody** [comment]
Fixed in 2417f44ab0
