### ISSUE TITLE
Registration: Popup message for empty "Battlefy Username" is unclear

### ISSUE THREAD

**Issue by Jaybomb** [daradermody/iigl#37]
# Symptom
- Clicking on “Register” displays "The form is not complete"

# Steps
- Company Email: jaybopper@hotmail.com
- Password: wasd
- Confirm Password: wasd
- Games Selected: LoL, OW, HS
- Clicked “Register”

**Comment by Jaybomb** [comment]
Message should say "Please enter your Battlefy Username"

**Comment by daradermody** [comment]
Fixed in 813d85c
